### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/mimir#1506]
v2.0.0 release checklist:

- [ ] Open source [Mimir](https://github.com/grafana/mimir/)
- [ ] Open source [Mimir-Prometheus](https://github.com/grafana/mimir-prometheus/)
- [ ] Open source [Rollout Operator](https://github.com/grafana/rollout-operator)
- [ ] Make [Mimir](https://hub.docker.com/repository/docker/grafana/mimir) Docker Hub repo public
- [ ] Make [mimirtool](https://hub.docker.com/repository/docker/grafana/mimirtool) Docker Hub repo public
- [ ] Make [Mimir Build Image](https://hub.docker.com/repository/docker/grafana/mimir-build-image) Docker Hub repo public
- [ ] Make [query-tee](https://hub.docker.com/repository/docker/grafana/query-tee) Docker Hub repo public
- [ ] Make [metaconvert](https://hub.docker.com/repository/docker/grafana/metaconvert) Docker Hub repo public
