### ISSUE TITLE
Prometheus Native Histogram support phase1

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#3478]
#### Basic Support Prometheus Native Histograms

Include Native Histogram support that was recently added to Prometheus in https://github.com/prometheus/prometheus/pull/11447

#### Describe the solution you'd like

Mimir to support ingestion and query of native histograms the same way as Prometheus.

Scope: able to ingest integer and float native histograms and query them back. Do not degrade existing float metrics performance.

Out of scope: recording rules resulting in native histograms, query sharding, optimization (see phase 2 : #4173 )

#### Describe alternatives you've considered

N/A

#### PR Numbers for changelog later
#4286 #4352 #4354 #4376 #4377 #4387 #4396 #4425 #4442 #4494 #4512 #4513

#### Additional context

Presentations (there are more, just picking two recent ones from PromCon 2022):
[Native histograms in Prometheus](https://www.youtube.com/watch?v=RDdlDRkuVL8&t=2780s)
[PromQL for native histograms](https://www.youtube.com/watch?v=RDdlDRkuVL8&t=4366s)

```[tasklist]
### Tasks
- [x] https://github.com/grafana/mimir/issues/3498
- [x] https://github.com/grafana/mimir-prometheus/issues/365
- [x] https://github.com/weaveworks/common/pull/262
- [x] If distributor receives a float and a histogram for the same timestamp keep only the histogram
- [ ] https://github.com/prometheus/client_golang/issues/1179
- [ ] https://github.com/grafana/mimir/issues/3713
- [x] https://github.com/grafana/mimir/issues/3714
- [ ] https://github.com/grafana/mimir/issues/3715
- [x] https://github.com/grafana/mimir/issues/3738
- [x] https://github.com/grafana/mimir/issues/3767
- [ ] https://github.com/grafana/mimir/issues/4158
- [x] https://github.com/grafana/mimir/issues/3944
- [x] https://github.com/grafana/mimir/issues/3947
- [x] https://github.com/grafana/mimir/issues/3949
- [x] https://github.com/grafana/mimir/issues/3958
- [x] https://github.com/grafana/mimir/issues/3980
- [x] https://github.com/grafana/mimir/issues/3981
- [x] Merge write path support to Mimir main
- [x] Merge read path support to Mimir main - might need further breakdown
- [ ] https://github.com/grafana/mimir/issues/4176
- [ ] https://github.com/grafana/mimir/issues/4191
- [ ] https://github.com/grafana/mimir/issues/4405
```
