### ISSUE TITLE
store-gateway: Use a pooling memory allocator for loading chunks from memcached

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#3772]
Store-gateways spend a significant portion of time reading data from memcached. Due to the way the memcached client used works, each read requires the client to allocate enough space for the data read. This memory is thread thrown away after the request is finished. This creates a lot of garbage and extra work for something only briefly used.

Modeling an approach based on the work done in #3756, we should attempt to pool memory used for reading from the chunks cache to reduce garbage generated and improve request speed.

From a dev cell, ~1/3 of memory allocated is by the memcached client:
![Screenshot 2022-12-19 at 13-28-38 Explore - Phlare (fire-dev-001) - Grafana](https://user-images.githubusercontent.com/1127373/208495338-14f3bf62-efac-45cc-b016-5a636bc19476.png)

----

### Tasks

* [x] Create a design document and get consensus on approach
* [x] Add optional caller supplied allocator for `grafana/gomemcache` - https://github.com/grafana/gomemcache/pull/8
* [x] Replace memcached client in `grafana/dskit` with `grafana/gomemcache` - https://github.com/grafana/dskit/pull/248
* [x] Add optional caller supplied allocator for `Cache` and memcached in `grafana/dskit`
* [ ] Introduce use of caller supplied allocator in Mimir store-gateway
    * [ ] Add ability to switch (or disable) allocator implementation used for caching based on config setting
    * [ ] Experiment with different allocators

**Comment by pracucci** [comment]
> We should probably remove the pooling in gomemcache https://github.com/grafana/gomemcache/pull/5 to avoid confusion. Better to have only a single way of doing something.

We should talk to Bryan and other projects using that fork (Mimir currently use an older commit not including it). I think that pooling would be very harder to use for the Mimir case, instead of passing the allocator directly to `GetMulti()` as a functional parameter.

**Comment by pracucci** [comment]
> My $0.02 is that the lifecycle of the memory being used for cache results is very request-oriented so it makes more sense to have the caller control the lifecycle of the memory instead of needing to return pooled bytes to the memecached client. 

💯

**Comment by bboreham** [comment]
This idea was raised in #285.
#2831 is an earlier attempt to use it in store-gateway.

**Comment by 56quarters** [comment]
This is incidentally being done as part of #3968. I will focus on testing memory pooling with the index cache.
