### ISSUE TITLE
Release 2.6.0

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#3979]
This issue is tracking the progress of the release 2.6.0. The release candidate is scheduled for the week of 16th or 23rd January.

### Publish the release candidate

- [x] Begin drafting the [release notes](https://github.com/grafana/mimir/blob/main/RELEASE.md#write-release-notes-document) #4002
  - Write release notes to `main`, then cherry pick them into the release branch
  - Don't block on it to publish the release candidate
- [x] Wait for any open PR we want to get merged before cutting the release candidate
  - [x] Eventually open a PR for every experimental feature we want to promote to stable #4003
  - [x] Eventually open a PR to remove any deprecated feature or configuration option that should be removed in this release #3982
- [x] Update `CHANGELOG.md`
  - [x] Run `./tools/release/check-changelog.sh LAST-RELEASE-TAG...main` and add missing PRs to CHANGELOG #4006
  - [x] Ensure CHANGELOG entries are [sorted by type](https://github.com/grafana/mimir/blob/main/docs/internal/contributing/README.md#changelog)
  - [x] Add a new section for the new release so that `## main / unreleased` is blank and at the top. The new section should say `## x.y.0-rc.0`.
- [x] Run `./tools/release/notify-changelog-cut.sh`
- [x] Run `make mixin-screenshots`
  - Before opening the PR, review all updated screenshots and ensure no sensitive data is disclosed
- [x] Create new release branch
  - [x] Create the branch
    ```bash
    git checkout main
    git checkout -b release-<version>
    git push -u origin release-<version>
    ```
  - [x] Remove "main / unreleased" section from the CHANGELOG
- [x] Publish the Mimir release candidate
  - [x] Update VERSION in the release branch and update CHANGELOG with version and release date.
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a pre-release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github)
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main)
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [x] Announce the release candidate on socials
- [x] Vendor the release commit of Mimir into Grafana Enterprise Metrics (GEM)
  - _This is addressed by Grafana Labs_

### Publish the stable release

- [x] Publish the Mimir stable release
  - [x] [Write release notes](https://github.com/grafana/mimir/blob/main/RELEASE.md#write-release-notes-document)
    - Ensure the any change to release notes in `main` has been cherry picked to the release branch
  - [x] Update version in release-<version> branch
    - VERSION
    - CHANGELOG
    - `operations/mimir/images.libsonnet` (`_images.mimir` and `_images.query_tee` fields)
    - `operations/mimir-rules-action/Dockerfile` (`grafana/mimirtool` image tag)
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github)
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main)
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [X] Announce the release on socials
  - [x] Open a PR to add the new version to the backward compatibility integration test (`integration/backward_compatibility_test.go`)
  - [X] [Publish dashboards to grafana.com](https://github.com/grafana/mimir/blob/main/RELEASE.md#publish-a-stable-release)
