### ISSUE TITLE
Support Redis as backend for all Mimir caches

### ISSUE THREAD

**Issue by 56quarters** [grafana/mimir#4236]
#### Is your feature request related to a problem? Please describe.

Some large organizations can't use software for which they are unable to buy support. While Memcached is simple to run, it falls under this category (no commercial support). 

#### Describe the solution you'd like

Since a cache is de facto required for GEM and Mimir, we'd also like to support Redis as a possible backend for the following caches: results, chunks, index, metadata. Redis support for caches used by GEM will be worked on independently.

#### Describe alternatives you've considered

Convincing large organizations They're Wrong and should just run Memcached.

#### Additional context

They didn't find that argument compelling.

See also #3762, #3832, grafana/dskit#245

----

```[tasklist]
### Tasks
- [X] #4237 
- [X] #4242
- [X] Design expected usage of Redis as cache (sentinel? cluster? master->replica setup?)
- [X] grafana/dskit#268
- [X] grafana/dskit#271
- [X] #4371
- [X] Test to ensure dashboards and alerts from the mixin work when using Redis #4427
- [ ] Update Mimir production tips to mention the option to use Redis
       - [ ] #4348
- [ ] Update Jsonnet to support Redis (WIP) 
      - [X] #4386 
      - [ ] https://github.com/grafana/deployment_tools/pull/60065 (WIP)
- [ ] ~Update Helm to support Redis~ no Helm changes needed for Redis 
```

**Comment by 56quarters** [comment]
> Design expected usage of Redis as cache (sentinel? cluster? master->replica setup?)

For this, I'm going to go with the simplest Redis setup possible (single instances for each cache). My reasoning is:

* Because we're using it as a cache, persistence isn't required: no need for the resiliency provided by replication, sentinel, or cluster mode.
* This keeps resource usage roughly on par with Memcached (don't need replicas or sentinels).
* We (Grafana) are not Redis experts and don't want support another distributed system within Mimir.
* Companies that need to use Redis because of support will be in a better position to know how to scale it.

**Comment by 56quarters** [comment]
I'm going to include https://github.com/grafana/dskit/issues/253 as part of this work. The multiple different cache abstractions in dskit are confusing. We (Mimir) are the only consumers of `RemoteCacheClient`, and only for the index cache in the store-gateway, so this shouldn't be too disruptive to Loki and Tempo.

**Comment by lamida** [comment]
> > Design expected usage of Redis as cache (sentinel? cluster? master->replica setup?)
> 
> For this, I'm going to go with the simplest Redis setup possible (single instances for each cache). My reasoning is:
> 
> * Because we're using it as a cache, persistence isn't required: no need for the resiliency provided by replication, sentinel, or cluster mode.
> * This keeps resource usage roughly on par with Memcached (don't need replicas or sentinels).
> * We (Grafana) are not Redis experts and don't want support another distributed system within Mimir.
> * Companies that need to use Redis because of support will be in a better position to know how to scale it.

I am going to start to work on Redis support in mimir-distributed helm chart. Considering we will just use single instance, I will just "embed" redis inside mimir-distributed helm chart, the same way as how we define Memcached, instead of using subchart for full-blown Redis helm chart for more complex requirements.

**Comment by lamida** [comment]
# How many Redis single server instances that we need?

Should we/users have separate Redis instances for different caches (results, metadata, index, chunks) like in the way Memcached is deployed now? There is one Memcached single server instance for each of the cache (so 4 Memcached servers). Does it make sense to just have one Redis instance handle all of the caches? 

Background of question: while working on [Jsonnet Redis support for Mimir](https://github.com/grafana/mimir/pull/4386), I find it is not straightforward to have multiple Redis in one Tanka environment, using grafana/jsonnet-libs/redis. I am still figuring it out though. I am a bit slow because I just realized I am still not so fluent with Jsonnet. There is no issue for Helm, we can just have as many Redis using helm.

# Should mimir-distributed helm chart also install Redis?

In the current in-progress [mimir-distributed Redis support PR](https://github.com/grafana/mimir/pull/4348), I am adding a template to make our chart to also install Redis single server instance (one for each result, metadata, index, and chunks). I was assuming making our chart to also install redis, is in scope of the project as I have written in [the comment above](https://github.com/grafana/mimir/issues/4236#issuecomment-1451427405).

However, from yesterday's weekly meeting, others think mimir-distributed helm chart, mustn't install Redis. Users should install Redis by themselves and mimir-distributed helm chart should only point to that Redis installation.

**Comment by 56quarters** [comment]
Closing this issue since as discussed offline:
* Minimal Jsonnet support for Redis config has been added
* Helm support will _not_ be added because we don't run Redis and cannot support people running it. It will be up to GEM/Mimir users to configure it themselves.
