### ISSUE TITLE
Release 2.8.0

### ISSUE THREAD

**Issue by lamida** [grafana/mimir#4739]
This issue is tracking the progress of the release 2.8.0. The release candidate is scheduled for the week of 17th April 2023.

When creating a source branch for a PR, avoid using `release-` prefix, except for the release branch, because branch with a such prefixes is protected and can't be pushed.

### Publish the release candidate

- [x] Begin drafting the [release notes](https://github.com/grafana/mimir/blob/main/RELEASE.md#write-release-notes-document) https://github.com/grafana/mimir/pull/4740
  - Create the release note PR to the main branch 
  - This step shouldn't block from publishing release candidate
  - After The PR is merged (which happen after RC is published), cherry-pick them into the release branch
- [x] Wait within the release day for any open PR we want to get merged before cutting the release candidate
  - [x] Eventually open a PR for every experimental feature we want to promote to stable. That has been by @charleskorn : #4557 and #4709.
  - [x] Eventually open a PR to remove any deprecated feature or configuration option that should be removed in this release. #4793 #4805 (missed to be done in 2.7)
- [x] Update `CHANGELOG.md`
  - [x] Run `./tools/release/check-changelog.sh LAST-RELEASE-TAG...main` and add missing PRs to CHANGELOG #4741
  - [x] Ensure CHANGELOG entries are [sorted by type](https://github.com/grafana/mimir/blob/main/docs/internal/contributing/README.md#changelog)
  - [x] Add a new section for the new release so that `## main / unreleased` is blank and at the top. The new section should say `## x.y.0-rc.0`. #4745 
- [x] Run `./tools/release/notify-changelog-cut.sh`
- [x] Run `make mixin-screenshots` #4754 
  - Before opening the PR, review all updated screenshots and ensure no sensitive data is disclosed
- [x] Create new release branch (branch name needs no minor version)
    ```bash
    git checkout main
    git checkout -b release-<version>
    git push -u origin release-<version>
    ```
  - [x] Remove "main / unreleased" section from the CHANGELOG #4750
- [x] Publish the Mimir release candidate
  - [x] Update VERSION in the release branch and update CHANGELOG with version and release date. 
    - #4750
    - #4806
    - #4841
    - Keep in mind this is a release candidate, so the version string in VERSION and CHANGELOG must end in `-rc.#`, where `#` is the release candidate number, starting at 0.
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a pre-release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github) 
   - [pre-release-draft 2.8.0-rc.0](https://github.com/grafana/mimir/releases/tag/untagged-bf26061a664fb5a50e05) 
   - [pre-release-draft 2.8.0-rc.1](https://github.com/grafana/mimir/releases/edit/untagged-31d5ac8d15ac576ddf90)
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [x] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main) 
    - #4760 (2.8.0-rc.0 merge)
    - #4819 (2.8.0-rc.1 merge)
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [x] Announce the release candidate on socials
- [ ] Vendor the release commit of Mimir into Grafana Enterprise Metrics (GEM)
  - _This is addressed by Grafana Labs_

### Publish the stable release

- [ ] Publish the Mimir stable release
  - [x] [Write release notes](https://github.com/grafana/mimir/blob/main/RELEASE.md#write-release-notes-document)
    - #4740  
    - Ensure the any change to release notes in `main` has been cherry picked to the release branch
  - [x] Update version in release-<version> branch by creating a PR, get it approved and merged #4887
    - VERSION
    - CHANGELOG (put all new changelogs under stable release and remove RC changelogs)
    - `operations/mimir/images.libsonnet` (`_images.mimir` and `_images.query_tee` fields)
    - `operations/mimir-rules-action/Dockerfile` (`grafana/mimirtool` image tag)
    - Run `make build-jsonnet-tests` to update the image in the test
  - [x] [Tag the release](https://github.com/grafana/mimir/blob/main/RELEASE.md#how-to-tag-a-release)
    ```bash
    git checkout release-<version>
    ./tools/release/tag-release.sh
    ```
  - [x] Wait until the CI pipeline succeeds
  - [x] [Create a release on GitHub](https://github.com/grafana/mimir/blob/main/RELEASE.md#creating-release-on-github) 
    ```bash
    git checkout release-<version>
    ./tools/release/create-draft-release.sh
    ```
  - [ ] [Merge the release branch release-<version> into main](https://github.com/grafana/mimir/blob/main/RELEASE.md#merging-release-branch-into-main) #4912
    ```bash
    ./tools/release/create-pr-to-merge-release-branch-to-main.sh
    ```
  - [x] Announce the release on socials
  - [x] Open a PR to add the new version to the backward compatibility integration test (`integration/backward_compatibility_test.go`) #4913
  - [x] [Publish dashboards to grafana.com](https://github.com/grafana/mimir/blob/main/RELEASE.md#publish-a-stable-release)

**Comment by lamida** [comment]
Completed https://github.com/grafana/mimir/releases/tag/mimir-2.8.0
