### ISSUE TITLE
Reduce ruler "list bucket" API calls

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#4941]
## Background

Analyzing the cost of object storage API calls at Grafana Labs we see the following split:
- Class A upload: 4%
- Class A listing: 55%
- Class B (reads): 41%

The 55% of API calls cost due to "list bucket" API calls is unexpected, so we investigated further. The split of such calls between components is:
- Ruler: 83%
- Compactor: 11%
- Everything else: 6%

**The ruler accounts for `55% * 83% = 46%` of object storage API calls cost**.

### Ruler's "List bucket" API calls

The ruler lists bucket objects in two functions:
- [ListAllUsers](https://github.com/grafana/mimir/blob/main/pkg/ruler/rulestore/bucketclient/bucket_client.go#L94)
- [ListRuleGroupsForUserAndNamespace](https://github.com/grafana/mimir/blob/main/pkg/ruler/rulestore/bucketclient/bucket_client.go#L108)

> ListAllUsers

This is used by:
- `/ruler/rule_groups` API endpoint
- `Ruler.syncRules()`

> ListRuleGroupsForUserAndNamespace

This is used by:
- `/ruler/rule_groups` API endpoint
- `POST /config/v1/rules/{namespace}` API endpoint (to create a new rule group)
- `GET /config/v1/rules API` endpoint (to get all rules of a tenant)
- `GET /config/v1/rules/{namespace}` API endpoint (to get all rules of a tenant belonging to a specific namespace)
- `Ruler.syncRules()`

> `Ruler.syncRules()`

After checking the number of Ruler API calls, we believe the biggest contributor to this cost is `Ruler.syncRules()`, called every `-ruler.poll-interval` (1m). Each ruler has to list all users and then, for each user belonging to their shuffle shard, list the user rules groups (recursively).

## Action plan

- [x] Introduce memcache support to cache "list bucket" operations with a short TTL, to cover the case the same tenant rule groups is listed by multiple ruler replicas within a polling interval
  - [x] Add optional cache support ([PR](https://github.com/grafana/mimir/pull/4950))
  - [x] Test in a Mimir dev cluster
- [x] Introduce event notification on changes, and relax the polling interval ([PR](https://github.com/grafana/mimir/pull/4975))
- [ ] Relax ruler's default poll interval

**Comment by pracucci** [comment]
## Ruler storage caching in a Mimir dev cluster

I've enabled the ruler storage cache in small Mimir dev cluster running 2 ruler instances. As expected, the "list objects" operation rate has been reduced by half:

![Screenshot 2023-05-09 at 13 45 53](https://github.com/grafana/mimir/assets/1701904/ba371bfa-7fd6-4993-a2b6-e4dbaa4f82fc)

**Comment by pracucci** [comment]
The change has been rolled out to production at Grafana Labs, including a change to `-ruler.poll-interval` from 1m to 10m. This resulted in a drastic reduction of "read" API calls issued from the ruler to object storage:

![Screenshot 2023-06-05 at 12 02 09](https://github.com/grafana/mimir/assets/1701904/724829ff-8e06-43ab-8174-0840091b948a)
