### ISSUE TITLE
native histograms: Reduce resolution instead of dropping when bucket limit is hit

### ISSUE THREAD

**Issue by gouthamve** [grafana/mimir#5367]
Currently when the buckets limit is hit with native histograms, we drop the sample. However, I think reducing resolution until the number of buckets are lower than the limit might be a better solution.

```[tasklist]
### Tasks
- [ ] implement down-scaling if sample has more buckets than the limit set for the tenant
- [ ] update the Mimir documentation as needed
- [ ] update the Mimir Helm chart documentation as needed
- [ ] update the Cloud metrics documentation as needed
```

**Comment by krajorama** [comment]
Note: if the native histogram contains an insane number of buckets, this might be prohibitively expensive, prone do DOS attack. I'd rather the client scraping/collecting does such reduction.

**Comment by gouthamve** [comment]
I thought reducing resolution is a light weight operation. I would figure parsing is the more expensive operation of the two and we'd have to parse it anyway before rejecting.

**Comment by beorn7** [comment]
I think this should be implemented in upstream Prometheus, see https://github.com/prometheus/prometheus/issues/12864 .

**Comment by beorn7** [comment]
OTOH Mimir remote-write receiver is probably code that doesn't exist in Prometheus. So this issue makes sense, too.
