### ISSUE TITLE
Docs: Move Configuration parameters to Configure

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#6336]
@jmichalek132 kindly provided feedback that the location of the configuration information is inconsistent across Tempo, Loki, and Mimir. This issue is to move Mimir’s content:

From:
_References_ > _Configuration parameters_

To:
_Configure_ > _Parameters_ (`menuTitle`) | _Configuration parameters_ (`Title`)

For Tempo, see related issue https://github.com/grafana/tempo/issues/3007.

```[tasklist]
### Tasks
- [x] Update aliases to moved files
- [x] Read about how to handle images in bundles; see https://grafana.com/docs/writers-toolkit/write/image-guidelines/#image-diagram-and-screenshot-guidelines, and open a ticket if this information is not in Writers’ Toolkit
- [x] Find Makefile target that builds the template and update the Makefile target path.
- [x] Build the website as a whole locally to check for local errors that do not appear if Mimir docs are built by themselves
```
