### ISSUE TITLE
Feature Request: Allow the mimir Alertmanager to support Grafana receivers and configuration

### ISSUE THREAD

**Issue by gotjosh** [grafana/mimir#6521]
#### Is your feature request related to a problem? Please describe.

As of version 9, Grafana uses the Alertmanager to handle notification delivery. However, to preserve backwards compatibility and avoid breaking changes, receivers within Grafana were not modified as they are configured differently.

To make sure we allow our users to consolidate all of their alerting configuration and delivery in one place, we propose that the mimir Alertmanager also supports the Grafana Alertmanager configuration and receivers. 

#### Describe the solution you'd like

We'd like the routing three to be the same but the configuration to be stored separately and only merged at runtime. As such, what we propose is the following:

```[tasklist]
### Tasks
- [ ] Allow Mimir to CRUD Grafana Alertmanager configuration via a public API.
- [ ] Allow Mimir to parse and validate eGrafana Alertmanager configuration via a public API.
- [ ] Allow Mimir to CRUD Grafana Alertmanager state (notification log and silences) via a Private API.
- [ ] Allow Mimir to unpromote/promote Grafana Alertmanager configuration; we'd like this to be a runtime toggle you can turn on and/or off for a given user.
- [ ] Allow Mimir to unpromote/promote Grafana Alertmanager state (notification log and silences); we'd like this to be a runtime toggle you can turn on and/or off for a given user.
- [ ] (Maybe) Allow Mimir to unpromote Grafana Alertmanager state
```

Our colleague @santihernandezc has already put together a POC of some of the changes necessary for this to work as expected: https://github.com/grafana/mimir/tree/santihernandezc/poc_grafana_alertmanager_configuration.

The only point which might be confusing is the idea behind promoting and unpromotion of configuration and state, which is a mechanism that exists to ease migrations without incurring downtime.

#### Describe alternatives you've considered

We considered running two separate Alertmanagers within the Mimir Alertmanager alongside two separate APIs but realised that this is not an unification and we would have two problems instead of just one.

The end goal is to eventually unify the configuration by removing the proprietary Grafana receivers, but by enabling the migration now, we can take an incremental approach.

#### Additional context

N/A
