### ISSUE TITLE
Docs: Re-order, revise, review, and refactor Mimir documentation

### ISSUE THREAD

**Issue by osg-grafana** [grafana/mimir#732]
**To see accurate status information about document development, [see the Grafana Labs org-wide project #120.](https://github.com/orgs/grafana/projects/120/views/1)**

**Co-ordinate any changes to this list that follows with Jack and Ursula.**

Refactor all Mimir documentation based on internal information architecture project underway by Docs Squad.

Thanks, @jdbaldry, for the collaboration on this list:

## Proposed structure for technical documentation

- [x] Collocate [Query sharding](https://github.com/grafana/mimir/pull/960) with the Query-frontend component
- [x] Move [Contributing](https://github.com/grafana/mimir/issues/952) to top level of repository.
- [x] [TO FIGURE OUT: Where does an explanation of how to issue cross-tenant queries and alerting/recording rules fit](https://github.com/grafana/mimir-squad/issues/517)
---
- [x] About Grafana Mimir
- [x] #1109
- [x]  [Getting started with Grafana Mimir](https://github.com/grafana/mimir/issues/868)
- [x] Migrate to Grafana Mimir
    - [x] [Migrating from Cortex](https://github.com/grafana/mimir/issues/703)
    - [x] [Migrating from Thanos or Prometheus](https://github.com/grafana/mimir/issues/876)
- [x] #1101
- [x] #999
    - [x] #1272
    - [x] #1273
    - [x] #1274
    - [x] #1078
    - [x] #1079
    - [x] #1080
    - [x] #1081
    - [x] #1082
    - [x] #1083
    - [x] #1084
    - [x] #1013
    - [x] #1110
    - [x] #1085
- [x] #1098
  - [x] #1086
  - [x] #1087
  - [x] #1105
  - [x] #1106
  - [x] #1088
  - [x] #1089
- [x] #1009
    - [x] #1090
    - [x] #1091
    - [x] #1092
    - [x] #1114
    - [x] #1093
    - [x] #1094
    - [x] #1095
    - [x] #1096
    - [x] #1111
    - [x] #1097
    - [x] #1103
    - [x] #1104
- [x] #1102
- [ ] [Reference: Configuration](https://github.com/grafana/mimir/issues/775), including [Configuration parameter lifecycle](https://github.com/grafana/mimir/pull/938) as a section rather than a separate file
- [x] [Reference: HTTP API](https://github.com/grafana/mimir/issues/734)

## To be re-ordered
- [x] #1108
- [x] #1113

## Add diagrams
   - [x] #1192
   - [x] #1194

## Terminology cleanup
- [x] https://github.com/grafana/mimir/issues/1150
- [x] https://github.com/grafana/mimir-squad/issues/547

**Comment by osg-grafana** [comment]
@jdbaldry and @osg-grafana have closed this issue by either opening up subsequent (smaller) issues or marked completed work done.

**Comment by osg-grafana** [comment]
@grafana/mimir-maintainers and the @grafana/docs-squad, thank you all for incredible work. Superb all around!
