### ISSUE TITLE
OTLP endpoint issues

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/mimir#8223]
## This ticket is to track all left works to be done in order to support otlp endpoint

bugs
- https://github.com/grafana/mimir/issues/6935
- https://github.com/grafana/mimir/issues/6696
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/mimir/issues/8240
- [ ] https://github.com/grafana/mimir/issues/8210
- [ ] https://github.com/grafana/mimir/issues/8185
- [ ] https://github.com/grafana/mimir/issues/8260
- [ ] https://github.com/grafana/mimir/issues/8269
- [ ] https://github.com/grafana/mimir/issues/8310
```
