### ISSUE TITLE
Helm: add support for GEM's federation-frontend

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#9672]
This is an issue to track the work we're doing for improving the federation-frontend. Part of the work is to add support for it in the mimir-distributed Helm chart.

The idea is to be able to deploy the component on its own and connect it to another GEM cluster. This means being able to disable most of the components that the chart deploys while leaving the necessary ones (PSP, config ConfigMap, license secret, meta monitoring resources, ...)

```[tasklist]
### Tasks
- [x] Add initial support for deploying federation-frontend https://github.com/grafana/mimir/pull/9673
- [x] Add `enabled` flags to most of the unrelated components, so none of their resources are rendered (deployments, services, service monitor...) https://github.com/grafana/mimir/pull/9734
- [x] Conditional config: 1) optionally set the `distributor` endpoint in the gateway config when the distributor is enabled so the gateway doesn't crash without a distributor; 2) disable GEM's `instrumentation` when the distributor isn't deployed, so there aren't a lot of warning logs. https://github.com/grafana/mimir/pull/9734
- [x] Documentation for deploying federation-frontend on its own along with an example values file https://github.com/grafana/mimir/pull/9735
```
